"""Outage table

Revision ID: acc5f4104849
Revises: 
Create Date: 2018-04-12 09:13:22.844958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc5f4104849'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oservice', sa.String(length=10), nullable=True),
    sa.Column('odate', sa.DateTime(), nullable=True),
    sa.Column('ohour', sa.Integer(), nullable=True),
    sa.Column('ominute', sa.Integer(), nullable=True),
    sa.Column('oampm', sa.String(length=1), nullable=True),
    sa.Column('olength', sa.Integer(), nullable=True),
    sa.Column('ocategory', sa.String(length=1), nullable=True),
    sa.Column('oreason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outage_ocategory'), 'outage', ['ocategory'], unique=False)
    op.create_index(op.f('ix_outage_oservice'), 'outage', ['oservice'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outage_oservice'), table_name='outage')
    op.drop_index(op.f('ix_outage_ocategory'), table_name='outage')
    op.drop_table('outage')
    # ### end Alembic commands ###
