"""empty message

Revision ID: 98bcbd052dec
Revises: acc5f4104849
Create Date: 2018-05-14 12:36:22.846394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bcbd052dec'
down_revision = 'acc5f4104849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i_pinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipaddress', sa.String(length=15), nullable=True),
    sa.Column('origincountry', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_i_pinfo_ipaddress'), 'i_pinfo', ['ipaddress'], unique=False)
    op.create_index(op.f('ix_i_pinfo_origincountry'), 'i_pinfo', ['origincountry'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_i_pinfo_origincountry'), table_name='i_pinfo')
    op.drop_index(op.f('ix_i_pinfo_ipaddress'), table_name='i_pinfo')
    op.drop_table('i_pinfo')
    # ### end Alembic commands ###
